### ISSUE TITLE
non-zero exit status 2147516566

### ISSUE THREAD

**Issue by Letmeload** [sthetix/NANDFIX#1]
got this error when push the GENERATE button.
![Error](https://github.com/user-attachments/assets/09d03cc2-03e6-4f67-857b-718f110918d9)

I worked my way through the new unbrick LVL3 video.

```
An error occurred during NAND files generation: Command 
"C:\Users\Admin\AppData\Local\Temp\_MEI179922\bin\EmmcHaccGen.exe" --keys 
"C:/Users/Admin/Deskop/prod.keys" --fw
"C:/Users/Admin/Desktop/Firmware-18.1.0" --mariko' 
returned non-zero exit status 2147516566.
```

**Comment by Letmeload** [comment]
Sorry... the mistake was that I had installed the .NET 8.0 SDK.
I really had to install runtime 7.0.20. Got that mixed up. Now it works.

**Comment by Letmeload** [comment]
Sorry... the mistake was that I had installed the .NET 8.0 SDK.
I really had to install runtime 7.0.20. Got that mixed up. Now it works.

**Comment by sthetix** [comment]
hello it is because you haven't installed the dot net 7.0.2
